name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build angle
        run: |
          mkdir -p build/linux/debian_bullseye_i386-sysroot
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Android-${{matrix.arch}}
          autoninja -C out/Android-${{matrix.arch}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angle
          path: angle/out
